version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check for updates once a week
    schedule:
      interval: 'weekly'
    # Specify labels for pull requests
    labels:
      - 'dependencies'
      - 'automerge'
    # Allow up to 10 open pull requests at a time
    open-pull-requests-limit: 10
    # Set version update strategy
    versioning-strategy: increase
    # Group dependencies updates
    groups:
      dependencies:
        patterns:
          - '*'
    # Ignore certain dependencies
    ignore:
      # Ignore major version updates for React
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'github_actions'
      - 'automerge'
